project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!**/drafts/**"
    - "!**/*draft*.qmd"

resources:
  - images/
  
website:
  title: "John Knight Stats"
  site-url: https://johnknightstats.com
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Articles"
        file: posts/index.qmd
      - text: "Projects"
        file: projects/index.qmd
      - text: "Papers"
        file: papers/index.qmd
      - text: "Tools"
        file: tools/index.qmd
      - text: "Dashboards"
        file: dashboards/index.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    includes:
      in-header: counter.html 

